In [3]:
import numpy as np

def sigmoid(x):
  s = 1/(1+np.exp(-x))

  return s

x = np.array([1,2,3,4,5])
print(sigmoid(x))
print(np.dot(x,x))


[0.73105858 0.88079708 0.95257413 0.98201379 0.99330715]
55


In [11]:
def sigmoid_derivative(x):
  s = sigmoid(x)
  return s*(1-s)

x = np.array([1,2,3])
print(sigmoid_derivative(x))

[0.19661193 0.10499359 0.04517666]


In [12]:
def image2vector(image):
  v = image.reshape((image.size), 1)
  return v

In [14]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print(image.shape)                
print(image2vector(image))


(3, 3, 2)
[[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]
